---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: chaos-demo-db
    release: primary
  name: chaos-demo-db
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
