---

apiVersion: v1
kind: Service
metadata:
  name: chaos-demo
  labels:
    app: chaos-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: chaos-demo
