---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-demo-for-db-ha
  labels:
    app: chaos-demo-for-db-ha
spec:
  selector:
    matchLabels:
      app: chaos-demo-for-db-ha
  template:
    metadata:
      labels:
        app: chaos-demo-for-db-ha
    spec:
      containers:
      - name: chaos-demo
        image: yejianhonghong/chaostoolkit-demo:0.0.1
        env:
        - name: DB
          value: chaos-demo-db-ha-mongodb-headless
        - name: VERSION
          value: "0.0.1"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 20Mi
